kind: Service
apiVersion: v1
metadata:
  name: centos-wildfly-loadbalancer
spec:
  selector:
    app: centos-wildfly
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080